---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pipeline-utilities

inputs:
- name: state
- name: generated-state
outputs:
- name: git-committed-state
params:
  GIT_COMMIT_USERNAME:
  GIT_COMMIT_EMAIL:
  GIT_COMMIT_MESSAGE:

run:
  path: bash
  args:
  - "-c"
  - |
      set -eux

      git clone secrets git-committed-state
      cp generated-state/state.yml git-committed-state/state.yml

      pushd git-committed-state
        if [[ -n $(git status --porcelain) ]]; then
          git config user.name "${GIT_COMMIT_USERNAME}"
          git config user.email "${GIT_COMMIT_EMAIL}"
          git add --all .
          git commit -m "${GIT_COMMIT_MESSAGE}"
        fi
      popd
