---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cwashburn/pipeline-utilities
outputs:
- name: auth
run:
  path: pipeline-utilities
  args: [ "opsman-auth", "--output-file", "auth/auth.yml" ]
