---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pipeline-utilities
inputs:
- name: input-folder1
- name: input-folder2
outputs:
- name: output-folder
run:
  path: bash
  args:
  - "-c"
  - |
      set -eux
      cp -r input-folder1/* output-folder/
      cp -r input-folder2/* output-folder/
