---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pipeline-utilities
inputs:
- name: auth
- name: config
- name: vars
  optional: true
- name: secrets
  optional: true
params:
  CONFIG_FILE:
  # - Required
  # - Filepath to the configuration yaml file
  # - The path is relative to the root of the `config` input
  VARS_FILES:
  # - Optional
  # - Filepath to the configuration var(s) yaml file
  # - The path is relative to root of the task build,
  #   so `vars` and `secrets` can be used.
  AUTH_CONFIG_FILE: auth.yml
  # - Optional
  # - Filepath of the authorization config YAML
  # - The path is relative to root of the `auth` input

run:
  path: bash
  args:
  - "-c"
  - |
      set -eux

      vars_files_args=("")
      for vf in ${VARS_FILES}
      do
        vars_files_args+=("--vars-file ${vf}")
      done

      # ${vars_files_args[@] needs to be globbed in order to pass through properly
      # shellcheck disable=SC2068
      pipeline-utilities uaa-configuration --auth-file "auth/${AUTH_CONFIG_FILE}" --config "config/${CONFIG_FILE}" ${vars_files_args[@]}
